on:
  push:
    branches: ["*"]

jobs:
  test:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        otp: ["25.0.4"]
        elixir: ["1.14.0-rc.1-otp-25"]
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      - name: Cache dependencies
        id: mix-cahe
        uses: actions/cache@v3
        with:
          path: |
            deps
            _build
            priv/plts
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('mix.lock') }}


      - name: Prepare Development Environment
        if: steps.mix-cache.outputs.cahe-hit != 'true'
        run: mix local.rebar --force && mix local.hex --force

      - name: mix deps.get
        if: steps.mix-cache.outputs.cahe-hit != 'true'
        run: mix deps.get

      - name: mix compile with check
        if: steps.mix-cache.outputs.cahe-hit != 'true'
        run: mix compile --all-warnings --warnings-as-errors

      - name: mix foramt with check
        run: mix format --check-formatted

      - name: docker compose up -d
        run: docker compose up -d

      - name: mix ecto test setup
        run: mix ecto_test_setup

      - name: mix test
        run: MIX_ENV=test mix test --max-failures 1 --warnings-as-errors
